package zipx.core

/** One entry in a [[StewardGroup]]'s `filter` list. Every field is optional, but Scala Steward rejects a filter with no
  * predicate at all, so [[ScalaStewardConfig.render]] refuses to emit an empty one.
  *
  * `version` takes Scala Steward's early-semver change names: `major`, `minor`, `patch`, `pre-release`,
  * `build-metadata`. Note that for 0.x versions the components shift left, so `0.0.51 -> 0.0.52` is classified `minor`,
  * not `patch`.
  */
final case class StewardFilter(
    group: Option[String] = None,
    artifact: Option[String] = None,
    version: Option[String] = None,
):
  def isEmpty: Boolean = group.isEmpty && artifact.isEmpty && version.isEmpty

/** One `pullRequests.grouping` entry: updates matching any filter land in this group's single PR.
  *
  * Groups are first-match-wins in list order, so narrower groups must come before broader ones.
  */
final case class StewardGroup(
    name: String,
    title: Option[String] = None,
    filter: List[StewardFilter] = Nil,
)

/** Renders the `pullRequests.grouping` block of a Scala Steward config (HOCON).
  *
  * This is written to `.github/.scala-steward.conf`, which the action hands to Scala Steward via its `repo-config`
  * input. That is the *global* config channel: it is merged ahead of the repo's own `.scala-steward.conf`
  * (`maybeGlobalRepoConfig |+| maybeRepoConfig`), and grouping lists concatenate. Since groups are first-match-wins and
  * the default list ends in a catch-all, a `pullRequests.grouping` block in the repo's own file would never be reached.
  * Extend [[ScalaStewardConfig.Defaults]] via `zipxStewardGrouping` instead.
  *
  * Keeping this separate from the repo file also means hand-written `updates.ignore` / `updates.retracted` entries stay
  * hand-owned; the two configs merge rather than replace.
  */
object ScalaStewardConfig:

  private val Header: String =
    """# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
      |# Scala Steward defaults, passed to the action via its `repo-config` input.
      |# Repo-specific overrides (updates.ignore, updates.retracted, ...) belong in the
      |# repo-root `.scala-steward.conf`, which is merged on top of this file.
      |# Grouping lives here because it is matched before the repo config: change it with
      |# `zipxStewardGrouping` in the build, not by adding pullRequests.grouping there.
      |""".stripMargin

  /** Family groups first, then a minor/major split, then a net.
    *
    * The trailing `{ group = "*" }` group is load-bearing, not decoration: Scala Steward's version filters need both
    * sides of a bump to parse as strict semver, and any update that fails to parse escapes every version-filtered
    * group. Without the net it would fall back to one PR per artifact.
    */
  val Defaults: List[StewardGroup] = List(
    StewardGroup(
      name = "earlyeffect",
      title = Some("Update early-effect dependencies"),
      filter = List(StewardFilter(group = Some("rocks.earlyeffect"))),
    ),
    StewardGroup(
      name = "zio",
      title = Some("Update ZIO dependencies"),
      filter = List(StewardFilter(group = Some("dev.zio"))),
    ),
    StewardGroup(
      name = "minor",
      title = Some("Minor and patch updates"),
      filter = List(
        StewardFilter(version = Some("minor")),
        StewardFilter(version = Some("patch")),
        StewardFilter(version = Some("pre-release")),
        StewardFilter(version = Some("build-metadata")),
      ),
    ),
    StewardGroup(
      name = "major",
      title = Some("Major updates"),
      filter = List(StewardFilter(version = Some("major"))),
    ),
    StewardGroup(
      name = "other",
      title = Some("Other updates"),
      filter = List(StewardFilter(group = Some("*"))),
    ),
  )

  def render(groups: List[StewardGroup]): String =
    require(groups.nonEmpty, "ScalaStewardConfig.render: groups must be non-empty")
    groups.foreach { g =>
      require(g.name.trim.nonEmpty, "ScalaStewardConfig.render: group name must be non-empty")
      require(g.filter.nonEmpty, s"ScalaStewardConfig.render: group '${g.name}' must have at least one filter")
      g.filter.foreach { f =>
        require(
          !f.isEmpty,
          s"ScalaStewardConfig.render: group '${g.name}' has a filter with no group/artifact/version predicate",
        )
      }
    }
    val entries = groups.map(renderGroup)
    Header + "\npullRequests.grouping = [\n" + entries.mkString(",\n") + "\n]\n"
  end render

  private def renderGroup(group: StewardGroup): String =
    val fields = List(
      Some(s"name = ${quote(group.name)}"),
      group.title.map(t => s"title = ${quote(t)}"),
      Some(s"filter = [${group.filter.map(renderFilter).mkString(", ")}]"),
    ).flatten
    s"  { ${fields.mkString(", ")} }"

  private def renderFilter(filter: StewardFilter): String =
    val fields = List(
      filter.group.map(g => s"group = ${quote(g)}"),
      filter.artifact.map(a => s"artifact = ${quote(a)}"),
      filter.version.map(v => s"version = ${quote(v)}"),
    ).flatten
    s"{ ${fields.mkString(", ")} }"

  /** HOCON quoted string: escape backslash and quote. Group/artifact globs and change names never need more. */
  private def quote(value: String): String =
    "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

  /** True when repo-root Steward config text sets a live `pullRequests.grouping` key.
    *
    * That block is unreachable under zipx's two-file model (generated grouping is merged first and ends in a
    * catch-all). Strips `#` line comments; missing / blank input is not a hit.
    */
  def repoRootGroupingIsDead(text: String): Boolean =
    text.linesIterator
      .map(_.replaceAll("""#.*$""", ""))
      .exists(line => """(?i)\bpullRequests\s*\.\s*grouping\b""".r.findFirstIn(line).isDefined)

  val RepoRootGroupingWarning: String =
    "repo-root .scala-steward.conf sets pullRequests.grouping, which is unreachable under zipx's generated " +
      "repo-config (first-match-wins, catch-all last). Set zipxStewardGrouping in the build instead."

end ScalaStewardConfig
