package zipx.core

import neotype.unwrap
import scala.quoted.*

/** Render and check the typed versions catalog; rewrite version literals in the catalog source. */
object ZipxCatalog:

  val PluginsPath: String         = "project/plugins.sbt"
  val BuildPropertiesPath: String = "project/build.properties"
  val DefaultVersionsFile: String = "project/ZipxVersions.scala"

  val GeneratedHeader: String =
    "# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  /** `project/plugins.sbt` is Scala 3 on sbt 2; `#` is not a comment there. */
  val PluginsHeader: String =
    "// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  def libs(coords: Seq[ZipxCoord]): List[Lib]       = coords.collect { case l: Lib => l }.toList
  def plugins(coords: Seq[ZipxCoord]): List[Plugin] = coords.collect { case p: Plugin => p }.toList

  /** Platform jars sbt / Scala.js / Scala Native inject into `libraryDependencies`. Not user catalog rows. */
  def isAutoPlatform(group: String, artifact: String): Boolean =
    val a = artifact
    (group == "org.scala-lang" && (
      a == "scala-library" || a == "scala-reflect" || a.startsWith("scala3-library") ||
        a.startsWith("scala3-compiler")
    )) || (group == "org.scala-js" && (
      // Scala.js injects already-crossed names (`scalajs-library_2.13`), unlike `%%` ModuleIDs whose `.name` is bare.
      a.startsWith("scalajs-library") || a.startsWith("scalajs-scalalib") ||
        a.startsWith("scalajs-test-bridge") || a.startsWith("scalajs-junit-test-plugin") ||
        a.startsWith("scalajs-compiler")
    )) || (group == "org.scala-native" && (
      // sbt-scala-native injects already-crossed names (`nativelib_native0.5_3`). Ignore toolchain artifacts only:
      // a user can still catalog a real Native library under this group.
      a.startsWith("nativelib") || a.startsWith("clib") || a.startsWith("posixlib") ||
        a.startsWith("windowslib") || a.startsWith("javalib") || a.startsWith("auxlib") ||
        a.startsWith("scala3lib") || a.startsWith("scalalib") ||
        a.startsWith("test-interface") || a.startsWith("junit-runtime") ||
        a.startsWith("junit-plugin") || a.startsWith("nscplugin")
    ))
  end isAutoPlatform

  /** `libraryDependencies` GAVs that are not a [[Lib]] row (same group, artifact, revision). */
  def extraLibs(declared: Seq[DeclaredGav], catalog: Seq[ZipxCoord]): List[DeclaredGav] =
    val allowed = libs(catalog).map(l => (l.group: String, l.artifact: String, l.version: String)).toSet
    declared
      .filterNot(d => isAutoPlatform(d.group, d.artifact))
      .filterNot(d => allowed.contains((d.group, d.artifact, d.revision)))
      .toList

  def scalaMismatch(declared: String, expected: Option[ScalaVersion]): Option[String] =
    expected.filter(exp => (exp: String) != declared).map { exp =>
      s"zipx: scalaVersion is '$declared' but zipxScala is '$exp'"
    }

  /** Load order generate writes: self plugins, then catalog plugins that are not already self-emitted. */
  def pluginInventory(plugins: Seq[Plugin], self: Seq[Plugin] = Nil): List[Plugin] =
    val selfKeys = self.map(p => (p.group: String, p.artifact: String)).toSet
    val rest     = plugins.filterNot(p => selfKeys.contains((p.group: String, p.artifact: String)))
    (self ++ rest).toList

  def renderPlugins(plugins: Seq[Plugin], self: Seq[Plugin] = Nil): String =
    val lines = pluginInventory(plugins, self).map(renderPluginLine)
    (PluginsHeader +: lines).mkString("\n") + "\n"

  def describePlugin(plugin: Plugin): String =
    val gav = s"${plugin.group} % ${plugin.artifact} % ${plugin.version}"
    if plugin.excludes.isEmpty then gav
    else
      val ex = plugin.excludes
        .map(e => e.artifact.fold(s"${e.organization}")(a => s"${e.organization}:${a}"))
        .mkString(", ")
      s"$gav excludeAll($ex)"

  def pluginsDrift(path: String, expected: List[Plugin], actual: List[Plugin]): String =
    s"""zipx: $path plugin list drifted.
       |expected: ${expected.map(describePlugin).mkString(", ")}
       |got: ${actual.map(describePlugin).mkString(", ")}
       |Run 'sbt zipxCatalogGenerate' (or zipxWorkflowGenerate) and commit the result.""".stripMargin

  def checkPlugins(path: String, parsed: Either[String, List[Plugin]], expected: List[Plugin]): Either[String, Unit] =
    parsed match
      case Left(err)                     => Left(s"zipx: $path: $err")
      case Right(got) if got != expected => Left(pluginsDrift(path, expected, got))
      case Right(_)                      => Right(())

  /** First duplicate group+artifact in a self-emit list. Generate refuses rather than writing two `addSbtPlugin` lines.
    */
  def duplicateSelf(self: Seq[Plugin]): Option[String] =
    self
      .map(p => (p.group: String, p.artifact: String))
      .groupBy(identity)
      .collectFirst {
        case ((g, a), copies) if copies.size > 1 => s"zipx: zipxSelfPlugins lists $g % $a twice"
      }

  def renderBuildProperties(sbt: SbtVersion): String =
    s"$GeneratedHeader\nsbt.version=${sbt: String}\n"

  def renderPluginLine(plugin: Plugin): String =
    val mid = s""""${plugin.group}" % "${plugin.artifact}" % "${plugin.version}""""
    if plugin.excludes.isEmpty then s"addSbtPlugin($mid)"
    else s"addSbtPlugin(($mid).excludeAll(${plugin.excludes.map(renderExclude).mkString(", ")}))"

  /** Lookup + classify every catalog row. `lookup` is `(group, artifact, current) => latest`. */
  def outdated(
      coords: Seq[ZipxCoord],
      lookup: (ZipxCoord) => Either[String, Option[String]],
      classify: VersionStrategy = VersionStrategy.npm,
      preRelease: PreRelease = PreRelease.Skip,
  ): Either[String, List[DepBump]] =
    coords.foldLeft[Either[String, List[DepBump]]](Right(Nil)) { (accE, coord) =>
      accE.flatMap { acc =>
        lookup(coord).map { latest =>
          latest
            .flatMap { candidate =>
              val kind = classify.classify(coord.version, candidate)
              Option.when(kind != BumpKind.None && preRelease.allows(kind)) {
                val to =
                  if kind == BumpKind.PreRelease then candidate
                  else classify.latestStable(List(candidate)).getOrElse(candidate)
                DepBump(coord, kind, to)
              }
            }
            .fold(acc)(acc :+ _)
        }
      }
    }

  def formatBumps(bumps: List[DepBump]): String =
    if bumps.isEmpty then "no outdated catalog versions"
    else
      bumps
        .map(b => s"- ${b.ctor} ${b.group} % ${b.artifact}: ${b.from} -> ${b.to} (${b.bump})")
        .mkString("\n")

  /** Rewrite `Lib("g", "a", "from")` / `Plugin("g", "a", "from")` constructors. `.mod` copies have no constructor;
    * those rows are skipped so the parent literal can carry the shared version.
    */
  def applyBumps(source: String, bumps: List[DepBump]): Either[String, String] =
    Right(
      bumps.foldLeft(source) { (src, bump) =>
        val from = constructorCall(bump.ctor, bump.group, bump.artifact, bump.from)
        val to   = constructorCall(bump.ctor, bump.group, bump.artifact, bump.to)
        if src.contains(from) then src.replace(from, to) else src
      }
    )

  def constructorCall(ctor: String, group: String, artifact: String, version: String): String =
    s"""$ctor("$group", "$artifact", "$version")"""

  /** Canonical `Pin("feed", "id", "ver", sha256 = "...", purl = "...")` as catalog apply rewrites it. */
  def pinConstructor(pin: Pin): String =
    val extras = List(
      pin.sha256.map(s => s"""sha256 = "$s""""),
      pin.purl.map(p => s"""purl = "${p: String}""""),
    ).flatten
    val extra = if extras.isEmpty then "" else extras.mkString(", ", ", ", "")
    s"""Pin("${pin.feed}", "${pin.id}", "${pin.version}"$extra)"""

  /** Rewrite [[Pin]] constructors. Missing constructor is Left, not a silent skip. */
  def applyPinBumps(source: String, bumps: List[PinBump]): Either[String, String] =
    applyAppliedPins(source, bumps.map(_.applied))

  def applyAppliedPins(source: String, items: List[AppliedPin]): Either[String, String] =
    items.foldLeft[Either[String, String]](Right(source)) { (accE, item) =>
      accE.flatMap { src =>
        val from = pinConstructor(item.pin)
        item.pin.bumped(item.candidate).flatMap { next =>
          val to = pinConstructor(next)
          if src.contains(from) then Right(src.replace(from, to))
          else
            Left(
              s"zipx: catalog has no Pin constructor for '${item.pin.feed}' '${item.pin.id}' ${item.pin.version}"
            )
        }
      }
    }

  /** Canonical `Action("owner/repo", "vX.Y.Z", sha = "…")` as catalog apply rewrites it. */
  def actionConstructor(action: Action): String =
    s"""Action("${action.name}", "${action.version}", sha = "${action.sha}")"""

  def applyActionBumps(source: String, bumps: List[ActionBump]): Either[String, String] =
    bumps.foldLeft[Either[String, String]](Right(source)) { (accE, bump) =>
      accE.flatMap { src =>
        val from = actionConstructor(bump.action)
        bump.action.bumped(bump.toVersion, bump.toSha).flatMap { next =>
          val to = actionConstructor(next)
          if src.contains(from) then Right(src.replace(from, to))
          else
            Left(
              s"zipx: catalog has no Action constructor for '${bump.action.name}' ${bump.action.version}. " +
                s"Paste ${actionConstructor(bump.action)} into project/ZipxVersions.scala, then sbt \"zipxActionUpdate yes\"."
            )
        }
      }
    }

  def formatActionBumps(bumps: List[ActionBump]): String =
    if bumps.isEmpty then "no outdated Action pins"
    else
      bumps
        .map(b => s"- Action ${b.action.name}: ${b.action.version} -> ${b.toVersion} (${b.bump})")
        .mkString("\n")

  def outdatedActions(
      rows: Seq[Action],
      lookup: Action => Either[String, Option[(String, String)]],
  ): Either[String, List[ActionBump]] =
    rows.foldLeft[Either[String, List[ActionBump]]](Right(Nil)) { (accE, action) =>
      accE.flatMap { acc =>
        lookup(action).map { latest =>
          latest.fold(acc) { (toVer, toSha) =>
            val kind = GitHubActionMeta.classify(action.version, toVer)
            if kind == BumpKind.None && toSha == (action.sha: String) then acc
            else if kind == BumpKind.None && toSha != (action.sha: String) then
              acc :+ ActionBump(action, BumpKind.Patch, toVer, toSha)
            else acc :+ ActionBump(action, kind, toVer, toSha)
          }
        }
      }
    }

  def catalogActionConstructors(pins: ActionPins): String =
    ActionPins.Field.values
      .map { f =>
        val ref = pins.field(f).unwrap
        val sha = ref.split('@').lastOption.getOrElse(ref)
        val ver = pins.version(f).getOrElse("v0")
        s"""  val ${f.key} = Action("${f.prefix}", "$ver", sha = "$sha")"""
      }
      .mkString("\n")

  def leftoverPinFileError(path: String, pins: ActionPins): String =
    s"""zipx: $path is leftover input. Action pins live in project/ZipxVersions.scala. Delete $path and paste:
       |
       |${catalogActionConstructors(pins)}
       |
       |Then sbt reload and sbt zipxWorkflowGenerate.""".stripMargin

  def unknownPinFeeds(feeds: Seq[PinFeed], pins: Seq[Pin]): Option[String] =
    val orphans = PinFeeds.orphanPins(feeds, pins)
    Option.when(orphans.nonEmpty) {
      val listed = orphans.map(p => s"'${p.feed}' '${p.id}'").mkString(", ")
      s"zipx: Pin val(s) have no matching zipxPinFeeds entry: $listed. Add a PinFeed or drop the Pin."
    }

  /** Every val on `catalog` whose type has an [[AsCoords]] given. Pass `[this.type]` from a trait so expansion sees the
    * concrete object. `Lib` / `Plugin` share one given; lists, `SbtVersion`, `ScalaVersion`, and named groups have
    * none, so they are skipped. `def` members are not vals: they are skipped. Rows come out in source declaration order
    * (parent traits, then the object), so generated `plugins.sbt` matches the catalog.
    */
  inline def coordsOf[A](inline catalog: A): Seq[ZipxCoord] =
    ${ coordsOfImpl[A]('catalog) }

  /** Every val on `catalog` whose type has an [[AsPins]] given. Same walk as [[coordsOf]]. */
  inline def pinsOf[A](inline catalog: A): Seq[Pin] =
    ${ pinsOfImpl[A]('catalog) }

  /** Every val on `catalog` whose type has an [[AsActions]] given. Same walk as [[coordsOf]]. */
  inline def actionsOf[A](inline catalog: A): Seq[Action] =
    ${ actionsOfImpl[A]('catalog) }

  /** Every val on `catalog` whose type has an [[AsShips]] given. Same walk as [[coordsOf]]. */
  inline def shipsOf[A](inline catalog: A): Seq[PublishedRow] =
    ${ shipsOfImpl[A]('catalog) }

  private def coordsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[ZipxCoord]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsCoords[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.coords($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[ZipxCoord] } else '{ ${ Expr.ofList(parts) }.flatten }
  end coordsOfImpl

  private def pinsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[Pin]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsPins[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.pins($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[Pin] } else '{ ${ Expr.ofList(parts) }.flatten }
  end pinsOfImpl

  private def actionsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[Action]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsActions[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.actions($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[Action] } else '{ ${ Expr.ofList(parts) }.flatten }
  end actionsOfImpl

  private def shipsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[PublishedRow]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsShips[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.ships($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[PublishedRow] } else '{ ${ Expr.ofList(parts) }.flatten }
  end shipsOfImpl

  private def catalogValParts[A: Type](using Quotes): List[(quotes.reflect.Symbol, quotes.reflect.TypeRepr)] =
    import quotes.reflect.*

    def skipClass(cls: Symbol): Boolean =
      cls.flags.is(Flags.JavaDefined) ||
        cls == defn.AnyClass || cls == defn.MatchableClass ||
        cls == defn.AnyRefClass || cls == defn.ObjectClass

    /** `fieldMembers` is reverse, and `Symbol.pos` is empty once the catalog is TASTy-loaded (`coords` expands in
      * `build.sbt`). ClassDef bodies from TASTy keep source order.
      */
    def valsInSourceOrder(cls: Symbol): List[Symbol] =
      val fromTree =
        try
          cls.tree match
            case cd: ClassDef =>
              Some(
                cd.body.collect {
                  case vd: ValDef if !vd.symbol.flags.is(Flags.Synthetic) => vd.symbol
                }
              )
            case _ => None
        catch case _: Exception => None
      fromTree.getOrElse(cls.declaredFields.filterNot(_.flags.is(Flags.Synthetic)))
    end valsInSourceOrder

    val tpe = TypeRepr.of[A].dealias
    tpe.baseClasses.filterNot(skipClass).reverse.flatMap(valsInSourceOrder).distinct.map { sym =>
      (sym, tpe.memberType(sym).widen.dealias)
    }
  end catalogValParts

  private def renderExclude(ex: ZipxExclude): String =
    ex.artifact match
      case None    => s"""ExclusionRule(organization = "${ex.organization}")"""
      case Some(a) => s"""ExclusionRule("${ex.organization}", "$a")"""

  /** Keep `addSbtPlugin` lines whose group+artifact are not catalog Plugin vals (self-emit), overlay catalog versions.
    */
  def mergePlugins(catalog: Seq[Plugin], existing: List[Plugin]): List[Plugin] =
    val catalogKeys = catalog.map(p => (p.group: String, p.artifact: String)).toSet
    val self        = existing.filterNot(p => catalogKeys.contains((p.group: String, p.artifact: String)))
    pluginInventory(catalog, self)
end ZipxCatalog
