package zipx.core

import neotype.unwrap
import scala.quoted.*

/** Render and check the typed versions catalog; rewrite version literals in the catalog source. */
object ZipxCatalog:

  val PluginsPath: String         = "project/plugins.sbt"
  val BuildPropertiesPath: String = "project/build.properties"
  val DefaultVersionsFile: String = "project/ZipxVersions.scala"

  val GeneratedHeader: String =
    "# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  /** `project/plugins.sbt` is Scala 3 on sbt 2; `#` is not a comment there. */
  val PluginsHeader: String =
    "// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  def libs(coords: Seq[ZipxCoord]): List[Lib]       = coords.collect { case l: Lib => l }.toList
  def plugins(coords: Seq[ZipxCoord]): List[Plugin] = coords.collect { case p: Plugin => p }.toList

  /** Platform jars sbt / Scala.js / Scala Native inject into `libraryDependencies`. Not user catalog rows. */
  def isAutoPlatform(group: String, artifact: String): Boolean =
    val a = artifact
    (group == "org.scala-lang" && (
      a == "scala-library" || a == "scala-reflect" || a.startsWith("scala3-library") ||
        a.startsWith("scala3-compiler")
    )) || (group == "org.scala-js" && (
      // Scala.js injects already-crossed names (`scalajs-library_2.13`), unlike `%%` ModuleIDs whose `.name` is bare.
      a.startsWith("scalajs-library") || a.startsWith("scalajs-scalalib") ||
        a.startsWith("scalajs-test-bridge") || a.startsWith("scalajs-junit-test-plugin") ||
        a.startsWith("scalajs-compiler")
    )) || (group == "org.scala-native" && (
      // sbt-scala-native injects already-crossed names (`nativelib_native0.5_3`). Ignore toolchain artifacts only:
      // a user can still catalog a real Native library under this group.
      a.startsWith("nativelib") || a.startsWith("clib") || a.startsWith("posixlib") ||
        a.startsWith("windowslib") || a.startsWith("javalib") || a.startsWith("auxlib") ||
        a.startsWith("scala3lib") || a.startsWith("scalalib") ||
        a.startsWith("test-interface") || a.startsWith("junit-runtime") ||
        a.startsWith("junit-plugin") || a.startsWith("nscplugin")
    ))
  end isAutoPlatform

  /** `libraryDependencies` GAVs that are not a [[Lib]] row (same group, artifact, revision). */
  def extraLibs(declared: Seq[DeclaredGav], catalog: Seq[ZipxCoord]): List[DeclaredGav] =
    val allowed = libs(catalog).map(l => (l.group: String, l.artifact: String, l.version: String)).toSet
    declared
      .filterNot(d => isAutoPlatform(d.group, d.artifact))
      .filterNot(d => allowed.contains((d.group, d.artifact, d.revision)))
      .toList

  def scalaMismatch(declared: String, expected: Option[ScalaVersion]): Option[String] =
    expected.filter(exp => (exp: String) != declared).map { exp =>
      s"zipx: scalaVersion is '$declared' but zipxScala is '$exp'"
    }

  /** Load order generate writes: self plugins, then catalog plugins that are not already self-emitted. */
  def pluginInventory(plugins: Seq[Plugin], self: Seq[Plugin] = Nil): List[Plugin] =
    val selfKeys = self.map(p => (p.group: String, p.artifact: String)).toSet
    val rest     = plugins.filterNot(p => selfKeys.contains((p.group: String, p.artifact: String)))
    (self ++ rest).toList

  def renderPlugins(plugins: Seq[Plugin], self: Seq[Plugin] = Nil): String =
    val lines = pluginInventory(plugins, self).map(renderPluginLine)
    (PluginsHeader +: lines).mkString("\n") + "\n"

  /** `addSbtPlugin` inventory from a committed `plugins.sbt`. Whitespace, `%` alignment, extra parens, and `//`
    * comments are trivia. Anything else (`resolvers`, `%%`, extra calls) is drift.
    */
  def parsePlugins(source: String): Either[String, List[Plugin]] =
    PluginsParser.parse(source)

  def describePlugin(plugin: Plugin): String =
    val gav = s"${plugin.group} % ${plugin.artifact} % ${plugin.version}"
    if plugin.excludes.isEmpty then gav
    else
      val ex = plugin.excludes
        .map(e => e.artifact.fold(s"${e.organization}")(a => s"${e.organization}:${a}"))
        .mkString(", ")
      s"$gav excludeAll($ex)"

  def pluginsDrift(path: String, expected: List[Plugin], actual: List[Plugin]): String =
    s"""zipx: $path plugin list drifted.
       |expected: ${expected.map(describePlugin).mkString(", ")}
       |got: ${actual.map(describePlugin).mkString(", ")}
       |Run 'sbt zipxCatalogGenerate' (or zipxWorkflowGenerate) and commit the result.""".stripMargin

  def checkPlugins(path: String, source: String, expected: List[Plugin]): Either[String, Unit] =
    parsePlugins(source) match
      case Left(err)                     => Left(s"zipx: $path: $err")
      case Right(got) if got != expected => Left(pluginsDrift(path, expected, got))
      case Right(_)                      => Right(())

  /** First duplicate group+artifact in a self-emit list. Generate refuses rather than writing two `addSbtPlugin` lines.
    */
  def duplicateSelf(self: Seq[Plugin]): Option[String] =
    self
      .map(p => (p.group: String, p.artifact: String))
      .groupBy(identity)
      .collectFirst {
        case ((g, a), copies) if copies.size > 1 => s"zipx: zipxSelfPlugins lists $g % $a twice"
      }

  def renderBuildProperties(sbt: SbtVersion): String =
    s"$GeneratedHeader\nsbt.version=${sbt: String}\n"

  def renderPluginLine(plugin: Plugin): String =
    val mid = s""""${plugin.group}" % "${plugin.artifact}" % "${plugin.version}""""
    if plugin.excludes.isEmpty then s"addSbtPlugin($mid)"
    else s"addSbtPlugin(($mid).excludeAll(${plugin.excludes.map(renderExclude).mkString(", ")}))"

  /** Lookup + classify every catalog row. `lookup` is `(group, artifact, current) => latest`. */
  def outdated(
      coords: Seq[ZipxCoord],
      lookup: (ZipxCoord) => Either[String, Option[String]],
      classify: VersionStrategy = VersionStrategy.npm,
      preRelease: PreRelease = PreRelease.Skip,
  ): Either[String, List[DepBump]] =
    coords.foldLeft[Either[String, List[DepBump]]](Right(Nil)) { (accE, coord) =>
      accE.flatMap { acc =>
        lookup(coord).map { latest =>
          latest
            .flatMap { candidate =>
              val kind = classify.classify(coord.version, candidate)
              Option.when(kind != BumpKind.None && preRelease.allows(kind)) {
                val to =
                  if kind == BumpKind.PreRelease then candidate
                  else classify.latestStable(List(candidate)).getOrElse(candidate)
                DepBump(coord, kind, to)
              }
            }
            .fold(acc)(acc :+ _)
        }
      }
    }

  def formatBumps(bumps: List[DepBump]): String =
    if bumps.isEmpty then "no outdated catalog versions"
    else
      bumps
        .map(b => s"- ${b.ctor} ${b.group} % ${b.artifact}: ${b.from} -> ${b.to} (${b.bump})")
        .mkString("\n")

  /** Rewrite `Lib("g", "a", "from")` / `Plugin("g", "a", "from")` constructors. `.mod` copies have no constructor;
    * those rows are skipped so the parent literal can carry the shared version.
    */
  def applyBumps(source: String, bumps: List[DepBump]): Either[String, String] =
    Right(
      bumps.foldLeft(source) { (src, bump) =>
        val from = constructorCall(bump.ctor, bump.group, bump.artifact, bump.from)
        val to   = constructorCall(bump.ctor, bump.group, bump.artifact, bump.to)
        if src.contains(from) then src.replace(from, to) else src
      }
    )

  def constructorCall(ctor: String, group: String, artifact: String, version: String): String =
    s"""$ctor("$group", "$artifact", "$version")"""

  /** Canonical `Pin("feed", "id", "ver", sha256 = "...", purl = "...")` as catalog apply rewrites it. */
  def pinConstructor(pin: Pin): String =
    val extras = List(
      pin.sha256.map(s => s"""sha256 = "$s""""),
      pin.purl.map(p => s"""purl = "${p: String}""""),
    ).flatten
    val extra = if extras.isEmpty then "" else extras.mkString(", ", ", ", "")
    s"""Pin("${pin.feed}", "${pin.id}", "${pin.version}"$extra)"""

  /** Rewrite [[Pin]] constructors. Missing constructor is Left, not a silent skip. */
  def applyPinBumps(source: String, bumps: List[PinBump]): Either[String, String] =
    applyAppliedPins(source, bumps.map(_.applied))

  def applyAppliedPins(source: String, items: List[AppliedPin]): Either[String, String] =
    items.foldLeft[Either[String, String]](Right(source)) { (accE, item) =>
      accE.flatMap { src =>
        val from = pinConstructor(item.pin)
        item.pin.bumped(item.candidate).flatMap { next =>
          val to = pinConstructor(next)
          if src.contains(from) then Right(src.replace(from, to))
          else
            Left(
              s"zipx: catalog has no Pin constructor for '${item.pin.feed}' '${item.pin.id}' ${item.pin.version}"
            )
        }
      }
    }

  /** Canonical `Action("owner/repo", "vX.Y.Z", sha = "…")` as catalog apply rewrites it. */
  def actionConstructor(action: Action): String =
    s"""Action("${action.name}", "${action.version}", sha = "${action.sha}")"""

  def applyActionBumps(source: String, bumps: List[ActionBump]): Either[String, String] =
    bumps.foldLeft[Either[String, String]](Right(source)) { (accE, bump) =>
      accE.flatMap { src =>
        val from = actionConstructor(bump.action)
        bump.action.bumped(bump.toVersion, bump.toSha).flatMap { next =>
          val to = actionConstructor(next)
          if src.contains(from) then Right(src.replace(from, to))
          else
            Left(
              s"zipx: catalog has no Action constructor for '${bump.action.name}' ${bump.action.version}. " +
                s"Paste ${actionConstructor(bump.action)} into project/ZipxVersions.scala, then sbt \"zipxActionUpdate yes\"."
            )
        }
      }
    }

  def formatActionBumps(bumps: List[ActionBump]): String =
    if bumps.isEmpty then "no outdated Action pins"
    else
      bumps
        .map(b => s"- Action ${b.action.name}: ${b.action.version} -> ${b.toVersion} (${b.bump})")
        .mkString("\n")

  def outdatedActions(
      rows: Seq[Action],
      lookup: Action => Either[String, Option[(String, String)]],
  ): Either[String, List[ActionBump]] =
    rows.foldLeft[Either[String, List[ActionBump]]](Right(Nil)) { (accE, action) =>
      accE.flatMap { acc =>
        lookup(action).map { latest =>
          latest.fold(acc) { (toVer, toSha) =>
            val kind = GitHubActionMeta.classify(action.version, toVer)
            if kind == BumpKind.None && toSha == (action.sha: String) then acc
            else if kind == BumpKind.None && toSha != (action.sha: String) then
              acc :+ ActionBump(action, BumpKind.Patch, toVer, toSha)
            else acc :+ ActionBump(action, kind, toVer, toSha)
          }
        }
      }
    }

  def catalogActionConstructors(pins: ActionPins): String =
    ActionPins.Field.values
      .map { f =>
        val ref = pins.field(f).unwrap
        val sha = ref.split('@').lastOption.getOrElse(ref)
        val ver = pins.version(f).getOrElse("v0")
        s"""  val ${f.key} = Action("${f.prefix}", "$ver", sha = "$sha")"""
      }
      .mkString("\n")

  def leftoverPinFileError(path: String, pins: ActionPins): String =
    s"""zipx: $path is leftover input. Action pins live in project/ZipxVersions.scala. Delete $path and paste:
       |
       |${catalogActionConstructors(pins)}
       |
       |Then sbt reload and sbt zipxWorkflowGenerate.""".stripMargin

  def unknownPinFeeds(feeds: Seq[PinFeed], pins: Seq[Pin]): Option[String] =
    val orphans = PinFeeds.orphanPins(feeds, pins)
    Option.when(orphans.nonEmpty) {
      val listed = orphans.map(p => s"'${p.feed}' '${p.id}'").mkString(", ")
      s"zipx: Pin val(s) have no matching zipxPinFeeds entry: $listed. Add a PinFeed or drop the Pin."
    }

  /** Every val on `catalog` whose type has an [[AsCoords]] given. Pass `[this.type]` from a trait so expansion sees the
    * concrete object. `Lib` / `Plugin` share one given; lists, `SbtVersion`, `ScalaVersion`, and named groups have
    * none, so they are skipped. `def` members are not vals: they are skipped. Rows come out in source declaration order
    * (parent traits, then the object), so generated `plugins.sbt` matches the catalog.
    */
  inline def coordsOf[A](inline catalog: A): Seq[ZipxCoord] =
    ${ coordsOfImpl[A]('catalog) }

  /** Every val on `catalog` whose type has an [[AsPins]] given. Same walk as [[coordsOf]]. */
  inline def pinsOf[A](inline catalog: A): Seq[Pin] =
    ${ pinsOfImpl[A]('catalog) }

  /** Every val on `catalog` whose type has an [[AsActions]] given. Same walk as [[coordsOf]]. */
  inline def actionsOf[A](inline catalog: A): Seq[Action] =
    ${ actionsOfImpl[A]('catalog) }

  private def coordsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[ZipxCoord]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsCoords[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.coords($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[ZipxCoord] } else '{ ${ Expr.ofList(parts) }.flatten }
  end coordsOfImpl

  private def pinsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[Pin]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsPins[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.pins($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[Pin] } else '{ ${ Expr.ofList(parts) }.flatten }
  end pinsOfImpl

  private def actionsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[Action]] =
    import quotes.reflect.*
    val parts = catalogValParts[A].flatMap { (sym, mt) =>
      mt.asType match
        case '[t] =>
          Expr.summon[AsActions[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.actions($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[Action] } else '{ ${ Expr.ofList(parts) }.flatten }
  end actionsOfImpl

  private def catalogValParts[A: Type](using Quotes): List[(quotes.reflect.Symbol, quotes.reflect.TypeRepr)] =
    import quotes.reflect.*

    def skipClass(cls: Symbol): Boolean =
      cls.flags.is(Flags.JavaDefined) ||
        cls == defn.AnyClass || cls == defn.MatchableClass ||
        cls == defn.AnyRefClass || cls == defn.ObjectClass

    /** `fieldMembers` is reverse, and `Symbol.pos` is empty once the catalog is TASTy-loaded (`coords` expands in
      * `build.sbt`). ClassDef bodies from TASTy keep source order.
      */
    def valsInSourceOrder(cls: Symbol): List[Symbol] =
      val fromTree =
        try
          cls.tree match
            case cd: ClassDef =>
              Some(
                cd.body.collect {
                  case vd: ValDef if !vd.symbol.flags.is(Flags.Synthetic) => vd.symbol
                }
              )
            case _ => None
        catch case _: Exception => None
      fromTree.getOrElse(cls.declaredFields.filterNot(_.flags.is(Flags.Synthetic)))
    end valsInSourceOrder

    val tpe = TypeRepr.of[A].dealias
    tpe.baseClasses.filterNot(skipClass).reverse.flatMap(valsInSourceOrder).distinct.map { sym =>
      (sym, tpe.memberType(sym).widen.dealias)
    }
  end catalogValParts

  private def renderExclude(ex: ZipxExclude): String =
    ex.artifact match
      case None    => s"""ExclusionRule(organization = "${ex.organization}")"""
      case Some(a) => s"""ExclusionRule("${ex.organization}", "$a")"""

  /** Closed dialect of generated `project/plugins.sbt`. Not a Scala parser. */
  private object PluginsParser:
    enum Tok:
      case Ident(value: String)
      case Str(value: String)
      case Percent(n: Int)
      case Other(ch: Char)
      case LParen, RParen, Dot, Comma, Eq
      case Eof

    final class Cursor(toks: Vector[Tok]):
      private var i = 0
      def peek: Tok =
        if i < toks.size then toks(i) else Tok.Eof
      def next(): Tok =
        val t = peek
        if t != Tok.Eof then i += 1
        t
      def takeIdent(expected: String): Either[String, Unit] =
        peek match
          case Tok.Ident(v) if v == expected =>
            next()
            Right(())
          case other => Left(s"expected '$expected', got ${tokShow(other)}")
      def take(expected: Tok): Either[String, Unit] =
        if peek == expected then
          next()
          Right(())
        else Left(s"expected ${tokShow(expected)}, got ${tokShow(peek)}")
    end Cursor

    def parse(source: String): Either[String, List[Plugin]] =
      tokenize(source).flatMap { toks =>
        val c = Cursor(toks)
        parseFile(c)
      }

    private def parseFile(c: Cursor): Either[String, List[Plugin]] =
      def loop(acc: List[Plugin]): Either[String, List[Plugin]] =
        c.peek match
          case Tok.Eof                   => Right(acc.reverse)
          case Tok.Ident("addSbtPlugin") =>
            parseAddSbtPlugin(c).flatMap(p => loop(p :: acc))
          case Tok.Ident(name) => Left(s"unexpected '$name'")
          case Tok.Other(ch)   => Left(s"unexpected '$ch'")
          case other           => Left(s"unexpected ${tokShow(other)}")
      loop(Nil)
    end parseFile

    private def parseAddSbtPlugin(c: Cursor): Either[String, Plugin] =
      for
        _      <- c.takeIdent("addSbtPlugin")
        _      <- c.take(Tok.LParen)
        plugin <- parsePluginExpr(c)
        _      <- c.take(Tok.RParen)
      yield plugin

    private def parsePluginExpr(c: Cursor): Either[String, Plugin] =
      def suffix(base: Plugin): Either[String, Plugin] =
        c.peek match
          case Tok.Dot =>
            for
              _  <- c.take(Tok.Dot)
              _  <- c.takeIdent("excludeAll")
              _  <- c.take(Tok.LParen)
              ex <- parseExcludes(c)
              _  <- c.take(Tok.RParen)
            yield base.copy(excludes = base.excludes ++ ex)
          case _ => Right(base)
      c.peek match
        case Tok.LParen =>
          for
            _     <- c.take(Tok.LParen)
            inner <- parsePluginExpr(c)
            _     <- c.take(Tok.RParen)
            out   <- suffix(inner)
          yield out
        case _ => parseGav(c).flatMap(suffix)
    end parsePluginExpr

    private def parseGav(c: Cursor): Either[String, Plugin] =
      for
        g <- takeStr(c)
        _ <- takePercent(c)
        a <- takeStr(c)
        _ <- takePercent(c)
        v <- takeStr(c)
        p <- mkPlugin(g, a, v, Nil)
      yield p

    private def parseExcludes(c: Cursor): Either[String, List[ZipxExclude]] =
      def loop(acc: List[ZipxExclude]): Either[String, List[ZipxExclude]] =
        c.peek match
          case Tok.RParen => Right(acc.reverse)
          case Tok.Comma  =>
            c.next()
            c.peek match
              case Tok.RParen => Right(acc.reverse)
              case _          => parseExclude(c).flatMap(ex => loop(ex :: acc))
          case _ =>
            if acc.nonEmpty then Left(s"expected ',' or ')', got ${tokShow(c.peek)}")
            else parseExclude(c).flatMap(ex => loop(ex :: acc))
      loop(Nil)
    end parseExcludes

    private def parseExclude(c: Cursor): Either[String, ZipxExclude] =
      for
        _  <- c.takeIdent("ExclusionRule")
        _  <- c.take(Tok.LParen)
        ex <- parseExcludeArgs(c)
        _  <- c.take(Tok.RParen)
      yield ex

    private def parseExcludeArgs(c: Cursor): Either[String, ZipxExclude] =
      c.peek match
        case Tok.Ident("organization") =>
          for
            _   <- c.takeIdent("organization")
            _   <- c.take(Tok.Eq)
            org <- takeStr(c)
            art <- optionalNamed(c, "name")
            _   <- skipTrailingComma(c)
            ex  <- mkExclude(org, art)
          yield ex
        case Tok.Str(_) =>
          for
            org <- takeStr(c)
            art <- optionalPositional(c)
            _   <- skipTrailingComma(c)
            ex  <- mkExclude(org, art)
          yield ex
        case other => Left(s"expected ExclusionRule args, got ${tokShow(other)}")

    private def optionalNamed(c: Cursor, name: String): Either[String, Option[String]] =
      c.peek match
        case Tok.Comma =>
          c.next()
          c.peek match
            case Tok.RParen                  => Right(None)
            case Tok.Ident(id) if id == name =>
              for
                _   <- c.takeIdent(name)
                _   <- c.take(Tok.Eq)
                str <- takeStr(c)
              yield Some(str)
            case other => Left(s"expected '$name' or ')', got ${tokShow(other)}")
        case _ => Right(None)

    private def optionalPositional(c: Cursor): Either[String, Option[String]] =
      c.peek match
        case Tok.Comma =>
          c.next()
          c.peek match
            case Tok.RParen => Right(None)
            case Tok.Str(_) => takeStr(c).map(Some(_))
            case other      => Left(s"expected string or ')', got ${tokShow(other)}")
        case _ => Right(None)

    private def skipTrailingComma(c: Cursor): Either[String, Unit] =
      c.peek match
        case Tok.Comma =>
          c.next()
          Right(())
        case _ => Right(())

    private def takeStr(c: Cursor): Either[String, String] =
      c.next() match
        case Tok.Str(s) => Right(s)
        case other      => Left(s"expected string, got ${tokShow(other)}")

    private def takePercent(c: Cursor): Either[String, Unit] =
      c.next() match
        case Tok.Percent(1) => Right(())
        case Tok.Percent(n) => Left(s"uses ${"%" * n}; generated plugins are %")
        case other          => Left(s"expected '%', got ${tokShow(other)}")

    private def mkPlugin(g: String, a: String, v: String, ex: List[ZipxExclude]): Either[String, Plugin] =
      for
        gg <- GroupId.make(g)
        aa <- ArtifactId.make(a)
        vv <- DepVersion.make(v)
      yield Plugin(gg, aa, vv, ex)

    private def mkExclude(org: String, art: Option[String]): Either[String, ZipxExclude] =
      for
        g <- GroupId.make(org)
        a <- art match
          case None    => Right(None)
          case Some(s) => ArtifactId.make(s).map(Some(_))
      yield ZipxExclude(g, a)

    private def tokShow(t: Tok): String =
      t match
        case Tok.Ident(v)   => s"'$v'"
        case Tok.Str(v)     => s"\"$v\""
        case Tok.Percent(n) => "'" + ("%" * n) + "'"
        case Tok.LParen     => "'('"
        case Tok.RParen     => "')'"
        case Tok.Dot        => "'.'"
        case Tok.Comma      => "','"
        case Tok.Eq         => "'='"
        case Tok.Other(ch)  => s"'$ch'"
        case Tok.Eof        => "end of file"

    private def tokenize(source: String): Either[String, Vector[Tok]] =
      val buf                                            = Vector.newBuilder[Tok]
      var i                                              = 0
      val n                                              = source.length
      def fail(msg: String): Either[String, Vector[Tok]] = Left(msg)
      while i < n do
        val ch = source.charAt(i)
        if ch.isWhitespace then i += 1
        else if ch == '/' && i + 1 < n && source.charAt(i + 1) == '/' then
          while i < n && source.charAt(i) != '\n' do i += 1
        else if ch == '"' then
          i += 1
          val start = i
          while i < n && source.charAt(i) != '"' do if source.charAt(i) == '\\' then i += 2 else i += 1
          if i >= n then return fail("unterminated string")
          buf += Tok.Str(source.substring(start, i))
          i += 1
        else if ch == '%' then
          var k = i
          while k < n && source.charAt(k) == '%' do k += 1
          buf += Tok.Percent(k - i)
          i = k
        else if ch.isLetter || ch == '_' then
          val start = i
          i += 1
          while i < n && { val c = source.charAt(i); c.isLetterOrDigit || c == '_' } do i += 1
          buf += Tok.Ident(source.substring(start, i))
        else
          ch match
            case '(' =>
              buf += Tok.LParen
              i += 1
            case ')' =>
              buf += Tok.RParen
              i += 1
            case '.' =>
              buf += Tok.Dot
              i += 1
            case ',' =>
              buf += Tok.Comma
              i += 1
            case '=' =>
              buf += Tok.Eq
              i += 1
            case _ =>
              buf += Tok.Other(ch)
              i += 1
        end if
      end while
      Right(buf.result())
    end tokenize
  end PluginsParser
end ZipxCatalog
