package zipx.core

import scala.quoted.*

/** Render and check the typed versions catalog; rewrite version literals in the catalog source. */
object ZipxCatalog:

  val PluginsPath: String         = "project/plugins.sbt"
  val BuildPropertiesPath: String = "project/build.properties"
  val DefaultVersionsFile: String = "project/ZipxVersions.scala"

  val GeneratedHeader: String =
    "# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  /** `project/plugins.sbt` is Scala 3 on sbt 2; `#` is not a comment there. */
  val PluginsHeader: String =
    "// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  def libs(coords: Seq[ZipxCoord]): List[Lib]       = coords.collect { case l: Lib => l }.toList
  def plugins(coords: Seq[ZipxCoord]): List[Plugin] = coords.collect { case p: Plugin => p }.toList

  /** Platform jars sbt / Scala.js inject into `libraryDependencies`. Not user catalog rows. */
  def isAutoPlatform(group: String, artifact: String): Boolean =
    val a = artifact
    (group == "org.scala-lang" && (
      a == "scala-library" || a == "scala-reflect" || a.startsWith("scala3-library") ||
        a.startsWith("scala3-compiler")
    )) || (group == "org.scala-js" && (
      // Scala.js injects already-crossed names (`scalajs-library_2.13`), unlike `%%` ModuleIDs whose `.name` is bare.
      a.startsWith("scalajs-library") || a.startsWith("scalajs-scalalib") ||
        a.startsWith("scalajs-test-bridge") || a.startsWith("scalajs-junit-test-plugin") ||
        a.startsWith("scalajs-compiler")
    ))
  end isAutoPlatform

  /** `libraryDependencies` GAVs that are not a [[Lib]] row (same group, artifact, revision). */
  def extraLibs(declared: Seq[DeclaredGav], catalog: Seq[ZipxCoord]): List[DeclaredGav] =
    val allowed = libs(catalog).map(l => (l.group: String, l.artifact: String, l.version: String)).toSet
    declared
      .filterNot(d => isAutoPlatform(d.group, d.artifact))
      .filterNot(d => allowed.contains((d.group, d.artifact, d.revision)))
      .toList

  def scalaMismatch(declared: String, expected: Option[ScalaVersion]): Option[String] =
    expected.filter(exp => (exp: String) != declared).map { exp =>
      s"zipx: scalaVersion is '$declared' but zipxScala is '$exp'"
    }

  def renderPlugins(plugins: Seq[Plugin], self: Seq[Plugin] = Nil): String =
    val selfKeys = self.map(p => (p.group: String, p.artifact: String)).toSet
    val rest     = plugins.filterNot(p => selfKeys.contains((p.group: String, p.artifact: String)))
    val lines    = (self ++ rest).map(renderPluginLine)
    (PluginsHeader +: lines).mkString("\n") + "\n"

  /** First duplicate group+artifact in a self-emit list. Generate refuses rather than writing two `addSbtPlugin` lines.
    */
  def duplicateSelf(self: Seq[Plugin]): Option[String] =
    self
      .map(p => (p.group: String, p.artifact: String))
      .groupBy(identity)
      .collectFirst {
        case ((g, a), copies) if copies.size > 1 => s"zipx: zipxSelfPlugins lists $g % $a twice"
      }

  def renderBuildProperties(sbt: SbtVersion): String =
    s"$GeneratedHeader\nsbt.version=${sbt: String}\n"

  def renderPluginLine(plugin: Plugin): String =
    val mid = s""""${plugin.group}" % "${plugin.artifact}" % "${plugin.version}""""
    if plugin.excludes.isEmpty then s"addSbtPlugin($mid)"
    else s"addSbtPlugin(($mid).excludeAll(${plugin.excludes.map(renderExclude).mkString(", ")}))"

  /** Lookup + classify every catalog row. `lookup` is `(group, artifact, current) => latest`. */
  def outdated(
      coords: Seq[ZipxCoord],
      lookup: (ZipxCoord) => Either[String, Option[String]],
      classify: VersionStrategy = VersionStrategy.npm,
  ): Either[String, List[DepBump]] =
    coords.foldLeft[Either[String, List[DepBump]]](Right(Nil)) { (accE, coord) =>
      accE.flatMap { acc =>
        lookup(coord).map { latest =>
          latest
            .flatMap { candidate =>
              val kind = classify.classify(coord.version, candidate)
              Option.when(kind != BumpKind.None) {
                val to = classify.latestStable(List(candidate)).getOrElse(candidate)
                DepBump(coord, kind, to)
              }
            }
            .fold(acc)(acc :+ _)
        }
      }
    }

  def formatBumps(bumps: List[DepBump]): String =
    if bumps.isEmpty then "no outdated catalog versions"
    else
      bumps
        .map(b => s"- ${b.ctor} ${b.group} % ${b.artifact}: ${b.from} -> ${b.to} (${b.bump})")
        .mkString("\n")

  /** Rewrite `Lib("g", "a", "from")` / `Plugin("g", "a", "from")` constructors. `.mod` copies have no constructor;
    * those rows are skipped so the parent literal can carry the shared version.
    */
  def applyBumps(source: String, bumps: List[DepBump]): Either[String, String] =
    Right(
      bumps.foldLeft(source) { (src, bump) =>
        val from = constructorCall(bump.ctor, bump.group, bump.artifact, bump.from)
        val to   = constructorCall(bump.ctor, bump.group, bump.artifact, bump.to)
        if src.contains(from) then src.replace(from, to) else src
      }
    )

  def constructorCall(ctor: String, group: String, artifact: String, version: String): String =
    s"""$ctor("$group", "$artifact", "$version")"""

  /** Every val on `catalog` whose type has an [[AsCoords]] given. Pass `[this.type]` from a trait so expansion sees the
    * concrete object. `Lib` / `Plugin` share one given; lists, `SbtVersion`, `ScalaVersion`, and named groups have
    * none, so they are skipped. `def` members are not vals: they are skipped. Rows come out in source declaration order
    * (parent traits, then the object), so generated `plugins.sbt` matches the catalog.
    */
  inline def coordsOf[A](inline catalog: A): Seq[ZipxCoord] =
    ${ coordsOfImpl[A]('catalog) }

  private def coordsOfImpl[A: Type](catalog: Expr[A])(using Quotes): Expr[Seq[ZipxCoord]] =
    import quotes.reflect.*

    def skipClass(cls: Symbol): Boolean =
      cls.flags.is(Flags.JavaDefined) ||
        cls == defn.AnyClass || cls == defn.MatchableClass ||
        cls == defn.AnyRefClass || cls == defn.ObjectClass

    /** `fieldMembers` is reverse, and `Symbol.pos` is empty once the catalog is TASTy-loaded (`coords` expands in
      * `build.sbt`). ClassDef bodies from TASTy keep source order.
      */
    def valsInSourceOrder(cls: Symbol): List[Symbol] =
      val fromTree =
        try
          cls.tree match
            case cd: ClassDef =>
              Some(
                cd.body.collect {
                  case vd: ValDef if !vd.symbol.flags.is(Flags.Synthetic) => vd.symbol
                }
              )
            case _ => None
        catch case _: Exception => None
      fromTree.getOrElse(cls.declaredFields.filterNot(_.flags.is(Flags.Synthetic)))
    end valsInSourceOrder

    val tpe   = TypeRepr.of[A].dealias
    val parts = tpe.baseClasses.filterNot(skipClass).reverse.flatMap(valsInSourceOrder).distinct.flatMap { sym =>
      val mt = tpe.memberType(sym).widen.dealias
      mt.asType match
        case '[t] =>
          Expr.summon[AsCoords[t]].map { tc =>
            val field = Select.unique(catalog.asTerm, sym.name).asExprOf[t]
            '{ $tc.coords($field) }
          }
    }
    if parts.isEmpty then '{ Seq.empty[ZipxCoord] } else '{ ${ Expr.ofList(parts) }.flatten }
  end coordsOfImpl

  private def renderExclude(ex: ZipxExclude): String =
    ex.artifact match
      case None    => s"""ExclusionRule(organization = "${ex.organization}")"""
      case Some(a) => s"""ExclusionRule("${ex.organization}", "$a")"""
end ZipxCatalog
