package zipx.workflow

import zio.test.*
import scala.collection.immutable.ListMap

object RenderSpec extends ZIOSpecDefault:

  extension (result: Either[String, String])
    private def yaml: String =
      result.fold(error => throw AssertionError(s"unexpected render failure: $error"), identity)

  private val sample = Workflow(
    name = "CI",
    on = Triggers(
      push = Some(BranchFilter(branches = List("main"), tags = List("v*"))),
      pullRequest = Some(BranchFilter()),
      workflowDispatch = true,
    ),
    jobs = ListMap(
      "test-workflow" -> Job(
        name = Some("Test zipx-workflow"),
        strategy = Some(Strategy(matrix = ListMap("scala" -> List("3.8.4")))),
        steps = List(
          Step(uses = Some(ActionRef("actions/checkout@v4"))),
          Step(name = Some("Test"), run = Some("sbt workflow/test")),
        ),
      ),
      "test-core" -> Job(
        needs = List("test-workflow"),
        `if` = Some("github.ref == 'refs/heads/main'"),
        env = ListMap("MY_TOKEN" -> "abc"),
        steps = List(Step(uses = Some(ActionRef("actions/checkout@v4")))),
      ),
    ),
  )

  private val expected =
    """# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
      |name: CI
      |"on":
      |  push:
      |    branches:
      |      - main
      |    tags:
      |      - v*
      |  pull_request: null
      |  workflow_dispatch: null
      |jobs:
      |  test-workflow:
      |    name: Test zipx-workflow
      |    runs-on: ubuntu-latest
      |    strategy:
      |      fail-fast: false
      |      matrix:
      |        scala:
      |          - "3.8.4"
      |    steps:
      |      - uses: actions/checkout@v4
      |      - name: Test
      |        run: sbt workflow/test
      |  test-core:
      |    runs-on: ubuntu-latest
      |    needs:
      |      - test-workflow
      |    if: github.ref == 'refs/heads/main'
      |    env:
      |      MY_TOKEN: abc
      |    steps:
      |      - uses: actions/checkout@v4
      |""".stripMargin

  def spec = suite("Render")(
    test("renders the golden GitHub Actions workflow exactly") {
      assertTrue(Render.render(sample).yaml == expected)
    },
    test("is deterministic: rendering twice yields identical bytes") {
      assertTrue(Render.render(sample).yaml == Render.render(sample).yaml)
    },
    test("renders the concurrency block, keeping an expression in cancel-in-progress unquoted-safe") {
      val wf = sample.copy(concurrency =
        Some(Concurrency("CI-${{ github.ref }}", "${{ !startsWith(github.ref, 'refs/tags/') }}"))
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("concurrency:"),
        out.contains("group: CI-${{ github.ref }}"),
        out.contains("cancel-in-progress:"),
        out.contains("!startsWith(github.ref, 'refs/tags/')"),
        !Render.render(sample).yaml.contains("concurrency"),
      )
    },
    test("prunes empty collections (no `{}` or `[]` in output)") {
      val out = Render.render(sample).yaml
      assertTrue(!out.contains("{}"), !out.contains("[]"))
    },
    test("renders multi-line values as YAML literal block scalars (not escaped \\n)") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        jobs = ListMap(
          "build" -> Job(steps =
            List(
              Step(
                name = Some("Cache"),
                uses = Some(ActionRef("actions/cache@v4")),
                `with` = ListMap("path" -> "~/.sbt\n~/.cache/sbt"),
              )
            )
          )
        ),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("path: |"),
        out.contains("~/.sbt"),
        out.contains("~/.cache/sbt"),
        !out.contains("""\n"""),
      )
    },
    test("reports a multi-line value that would render as unreadable YAML") {
      def render(run: String): Either[String, String] =
        Render.render(
          Workflow(
            name = "CI",
            on = Triggers(push = Some(BranchFilter(branches = List("main")))),
            jobs = ListMap("build" -> Job(steps = List(Step(run = Some(run))))),
          )
        )
      def failure(run: String): Option[String] = render(run).left.toOption
      val soh                                  = 0x01.toChar
      val withControlChar                      = s"echo a\necho ${soh}b"
      assertTrue(
        failure("echo a\r\necho b").exists(_.contains("line 1")),
        failure(withControlChar).exists(_.contains("control character")),
        failure("echo a\n\techo b").exists(_.contains("line 2")),
        failure("echo a\n\techo b").exists(_.contains("tab")),
        failure("echo\ta\necho b").isEmpty,
        render("echo a\necho b").yaml.contains("run: |"),
      )
    },
    test("renders a job's environment binding and env block") {
      val wf = Workflow(
        name = "CD",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        jobs = ListMap(
          "deploy-prod" -> Job(
            name = Some("deploy (prod)"),
            environment = Some("production"),
            permissions = ListMap("id-token" -> "write", "contents" -> "read"),
            env = ListMap("DEPLOY_ROLE" -> "${{ secrets.PROD_ROLE }}", "TIER" -> "prod"),
            steps = List(Step(uses = Some(ActionRef("actions/checkout@v4")))),
          )
        ),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("environment: production"),
        out.contains("DEPLOY_ROLE: ${{ secrets.PROD_ROLE }}"),
        out.contains("TIER: prod"),
        out.contains("id-token: write"),
        out.contains("contents: read"),
      )
    },
    test("runs-on renders as a scalar for one label and a sequence for many") {
      def render(labels: List[String]) =
        Render
          .render(
            Workflow(
              name = "CI",
              on = Triggers(push = Some(BranchFilter(branches = List("main")))),
              jobs =
                ListMap("j" -> Job(runsOn = labels, steps = List(Step(uses = Some(ActionRef("actions/checkout@v4")))))),
            )
          )
          .yaml
      val single = render(List("ubuntu-latest"))
      val multi  = render(List("self-hosted", "linux"))
      assertTrue(
        single.contains("runs-on: ubuntu-latest"),
        !single.contains("runs-on:\n      -"),
        multi.contains("- self-hosted"),
        multi.contains("- linux"),
      )
    },
    test("reusable workflow call jobs emit uses/with and omit runs-on/steps") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(workflowDispatch = true),
        jobs = ListMap(
          "docs" -> Job(
            name = Some("docs"),
            runsOn = Nil,
            permissions = ListMap("pages" -> "write", "id-token" -> "write", "contents" -> "read"),
            uses = Some(ActionRef("early-effect/.github/.github/workflows/specular-docs.yml@main")),
            `with` = ListMap("sbt-project" -> "docs"),
          )
        ),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("uses: early-effect/.github/.github/workflows/specular-docs.yml@main"),
        out.contains("sbt-project: docs"),
        out.contains("pages: write"),
        out.contains("workflow_dispatch: null"),
        !out.contains("runs-on:"),
        !out.contains("steps:"),
      )
    },
    test("schedule cron expressions render under on.schedule") {
      val wf = Workflow(
        name = "Scala Steward",
        on = Triggers(schedule = List(Cron.weekly(DayOfWeek.Sunday)), workflowDispatch = true),
        jobs = ListMap(
          "scala-steward" -> Job(steps =
            List(Step(uses = Some(ActionRef("scala-steward-org/scala-steward-action@v2"))))
          )
        ),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("schedule:"),
        out.contains("cron:") && (out.contains("cron: \"0 0 * * 0\"") || out.contains("cron: 0 0 * * 0")),
        out.contains("workflow_dispatch: null"),
      )
    },
    test("renderBody is render without the generated-by header") {
      val body = Render.renderBody(sample).yaml
      val full = Render.render(sample).yaml
      assertTrue(
        !body.startsWith("#"),
        full == s"${Render.header}\n$body\n",
      )
    },
    test("renderJob matches the jobs: slice of renderBody") {
      val body     = Render.renderBody(sample).yaml
      val job      = Render.renderJob("test-core", sample.jobs("test-core")).yaml
      val indented = job.linesIterator.map(l => if l.isEmpty then l else s"  $l").mkString("\n")
      assertTrue(
        body.contains(indented),
        job.contains("test-core:"),
        job.contains("if: github.ref == 'refs/heads/main'"),
        job.contains("MY_TOKEN: abc"),
        !job.contains("name: CI"),
        !job.contains("jobs:"),
      )
    },
    test("renderJobs preserves ListMap order and matches each renderJob") {
      val both = Render.renderJobs(sample.jobs).yaml
      assertTrue(
        both.indexOf("test-workflow:") < both.indexOf("test-core:"),
        both.contains(Render.renderJob("test-workflow", sample.jobs("test-workflow")).yaml.trim) ||
          both.startsWith("test-workflow:"),
        Render.renderJobs(ListMap("test-core" -> sample.jobs("test-core"))).yaml ==
          Render.renderJob("test-core", sample.jobs("test-core")).yaml,
      )
    },
    test("renderSteps encodes a step sequence") {
      val steps = Render
        .renderSteps(
          List(
            Step(uses = Some(ActionRef("actions/checkout@v4"))),
            Step(name = Some("Test"), run = Some("sbt test")),
          )
        )
        .yaml
      assertTrue(
        steps.contains("- uses: actions/checkout@v4"),
        steps.contains("- name: Test"),
        steps.contains("run: sbt test"),
      )
    },
    test("renderMapping prints a flat string map") {
      val out = Render.renderMapping(ListMap("packages" -> "write", "contents" -> "read")).yaml
      assertTrue(
        out.contains("packages: write"),
        out.contains("contents: read"),
        Render.renderMapping(Map.empty).yaml == "",
      )
    },
    test("Triggers.workflowCall renders workflow_call trigger") {
      val wf = Workflow(
        name = "Reusable",
        on = Triggers(workflowCall = true),
        jobs = ListMap("run" -> Job(steps = List(Step(run = Some("echo hi"))))),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("workflow_call: null"),
        !out.contains("push:"),
        !out.contains("pull_request:"),
      )
    },

    test("workflow-level permissions render before jobs") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        permissions = ListMap("contents" -> "read", "issues" -> "write"),
        jobs = ListMap("j" -> Job(steps = List(Step(run = Some("echo hi"))))),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("permissions:"),
        out.contains("contents: read"),
        out.contains("issues: write"),
      )
      val lines       = out.linesIterator.toList
      val permIdx     = lines.indexWhere(_.startsWith("permissions:"))
      val firstJobIdx = lines.indexWhere(l => l.trim == "j:" || l.trim.startsWith("j: "))
      assertTrue(permIdx > 0, firstJobIdx > permIdx)

    },

    test("workflow-level env renders before jobs") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        env = ListMap("GLOBAL_VAR" -> "value"),
        jobs = ListMap("j" -> Job(steps = List(Step(run = Some("echo hi"))))),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("env:"),
        out.contains("GLOBAL_VAR: value"),
      )
      val lines       = out.linesIterator.toList
      val envIdx      = lines.indexWhere(_.startsWith("env:"))
      val firstJobIdx = lines.indexWhere(l => l.trim == "j:" || l.trim.startsWith("j: "))
      assertTrue(envIdx > 0, firstJobIdx > envIdx)

    },

    test("BranchFilter.paths render under push/pull_request triggers") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(
          push = Some(BranchFilter(paths = List(".github/**", "modules/**"))),
          pullRequest = Some(BranchFilter(paths = List("modules/**"))),
        ),
        jobs = ListMap("j" -> Job(steps = List(Step(run = Some("echo hi"))))),
      )
      val out = Render.render(wf).yaml
      assertTrue(
        out.contains("paths:"),
        out.contains(".github/**"),
        out.contains("modules/**"),
      )
    },

    test("is deterministic: rendering 100 times yields identical bytes") {
      val results = List.fill(100)(Render.render(sample).yaml)
      assertTrue(results.distinct.size == 1)
    },
    test("a step GitHub would reject is a Left, not an exception, and names the step") {
      val both = Step(name = Some("Confused"), uses = Some(ActionRef("actions/checkout@v4")), run = Some("echo hi"))
      val wf   = sample.copy(jobs = ListMap("build" -> Job(steps = List(both))))
      assertTrue(
        Render.render(wf).left.exists(_.contains("both uses and run")),
        Render.render(wf).left.exists(_.contains("'Confused'")),
        Render.renderSteps(List(Step())).left.exists(_.contains("neither uses nor run")),
        Render.renderJob("build", Job(steps = List(both))).isLeft,
        Render.renderJobs(ListMap("build" -> Job(steps = List(both)))).isLeft,
        Render.renderBody(wf).isLeft,
      )
    },
  )
end RenderSpec
