package zipx.workflow

import zio.test.*
import scala.collection.immutable.ListMap

object RenderSpec extends ZIOSpecDefault:

  // A workflow exercising every render concern: underscore trigger keys, kebab job/step
  // keys, unquoted ints, matrix, needs, env (verbatim keys), if:, and empty-collection pruning.
  private val sample = Workflow(
    name = "CI",
    on = Triggers(
      push = Some(BranchFilter(branches = List("main"), tags = List("v*"))),
      pullRequest = Some(BranchFilter()),
      workflowDispatch = true,
    ),
    jobs = ListMap(
      "test-workflow" -> Job(
        name = Some("Test zipx-workflow"),
        strategy = Some(Strategy(matrix = ListMap("scala" -> List("3.8.4")))),
        steps = List(
          Step(uses = Some("actions/checkout@v4")),
          Step(name = Some("Test"), run = Some("sbt workflow/test")),
        ),
      ),
      "test-core" -> Job(
        needs = List("test-workflow"),
        `if` = Some("github.ref == 'refs/heads/main'"),
        env = ListMap("MY_TOKEN" -> "abc"),
        steps = List(Step(uses = Some("actions/checkout@v4"))),
      ),
    ),
  )

  private val expected =
    """# Generated by zipx — do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
      |name: CI
      |"on":
      |  push:
      |    branches:
      |      - main
      |    tags:
      |      - v*
      |  pull_request: null
      |  workflow_dispatch: null
      |jobs:
      |  test-workflow:
      |    name: Test zipx-workflow
      |    runs-on: ubuntu-latest
      |    strategy:
      |      fail-fast: false
      |      matrix:
      |        scala:
      |          - "3.8.4"
      |    steps:
      |      - uses: actions/checkout@v4
      |      - name: Test
      |        run: sbt workflow/test
      |  test-core:
      |    runs-on: ubuntu-latest
      |    needs:
      |      - test-workflow
      |    if: github.ref == 'refs/heads/main'
      |    env:
      |      MY_TOKEN: abc
      |    steps:
      |      - uses: actions/checkout@v4
      |""".stripMargin

  def spec = suite("Render")(
    test("renders the golden GitHub Actions workflow exactly") {
      assertTrue(Render.render(sample) == expected)
    },
    test("is deterministic — rendering twice yields identical bytes") {
      assertTrue(Render.render(sample) == Render.render(sample))
    },
    test("prunes empty collections (no `{}` or `[]` in output)") {
      val out = Render.render(sample)
      assertTrue(!out.contains("{}"), !out.contains("[]"))
    },
    test("renders multi-line values as YAML literal block scalars (not escaped \\n)") {
      // A step whose `with` carries a multi-path value (like actions/cache path:).
      val wf = Workflow(
        name = "CI",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        jobs = ListMap(
          "build" -> Job(steps =
            List(
              Step(
                name = Some("Cache"),
                uses = Some("actions/cache@v4"),
                `with` = ListMap("path" -> "~/.sbt\n~/.cache/sbt"),
              )
            )
          )
        ),
      )
      val out = Render.render(wf)
      assertTrue(
        out.contains("path: |"), // literal block scalar marker
        out.contains("~/.sbt"),
        out.contains("~/.cache/sbt"),
        !out.contains("""\n"""), // never an escaped newline
      )
    },
    test("renders a job's environment binding and env block") {
      val wf = Workflow(
        name = "CD",
        on = Triggers(push = Some(BranchFilter(branches = List("main")))),
        jobs = ListMap(
          "deploy-prod" -> Job(
            name = Some("deploy (prod)"),
            environment = Some("production"),
            permissions = ListMap("id-token" -> "write", "contents" -> "read"),
            env = ListMap("DEPLOY_ROLE" -> "${{ secrets.PROD_ROLE }}", "TIER" -> "prod"),
            steps = List(Step(uses = Some("actions/checkout@v4"))),
          )
        ),
      )
      val out = Render.render(wf)
      assertTrue(
        out.contains("environment: production"),
        out.contains("DEPLOY_ROLE: ${{ secrets.PROD_ROLE }}"),
        out.contains("TIER: prod"),
        out.contains("id-token: write"),
        out.contains("contents: read"),
      )
    },
    test("runs-on renders as a scalar for one label and a sequence for many") {
      def render(labels: List[String]) =
        Render.render(
          Workflow(
            name = "CI",
            on = Triggers(push = Some(BranchFilter(branches = List("main")))),
            jobs = ListMap("j" -> Job(runsOn = labels, steps = List(Step(uses = Some("actions/checkout@v4"))))),
          )
        )
      val single = render(List("ubuntu-latest"))
      val multi  = render(List("self-hosted", "linux"))
      assertTrue(
        single.contains("runs-on: ubuntu-latest"), // scalar
        !single.contains("runs-on:\n      -"),     // not a sequence
        multi.contains("- self-hosted"),           // sequence
        multi.contains("- linux"),
      )
    },
    test("reusable workflow call jobs emit uses/with and omit runs-on/steps") {
      val wf = Workflow(
        name = "CI",
        on = Triggers(workflowDispatch = true),
        jobs = ListMap(
          "docs" -> Job(
            name = Some("docs"),
            runsOn = Nil,
            permissions = ListMap("pages" -> "write", "id-token" -> "write", "contents" -> "read"),
            uses = Some("early-effect/.github/.github/workflows/specular-docs.yml@main"),
            `with` = ListMap("sbt-project" -> "docs"),
          )
        ),
      )
      val out = Render.render(wf)
      assertTrue(
        out.contains("uses: early-effect/.github/.github/workflows/specular-docs.yml@main"),
        out.contains("sbt-project: docs"),
        out.contains("pages: write"),
        out.contains("workflow_dispatch: null"),
        !out.contains("runs-on:"),
        !out.contains("steps:"),
      )
    },
    test("schedule cron expressions render under on.schedule") {
      val wf = Workflow(
        name = "Scala Steward",
        on = Triggers(schedule = List(Cron.weekly(DayOfWeek.Sunday)), workflowDispatch = true),
        jobs = ListMap(
          "scala-steward" -> Job(steps = List(Step(uses = Some("scala-steward-org/scala-steward-action@v2"))))
        ),
      )
      val out = Render.render(wf)
      assertTrue(
        out.contains("schedule:"),
        out.contains("cron: 0 0 * * 0") || out.contains("""cron: "0 0 * * 0""""),
        out.contains("workflow_dispatch: null"),
      )
    },
    test("renderBody is render without the generated-by header") {
      val body = Render.renderBody(sample)
      val full = Render.render(sample)
      assertTrue(
        !body.startsWith("#"),
        full == s"${Render.header}\n$body\n",
      )
    },
    test("renderJob matches the jobs: slice of renderBody") {
      val body = Render.renderBody(sample)
      val job  = Render.renderJob("test-core", sample.jobs("test-core"))
      // Indent job fragment as it appears under jobs: (2 spaces).
      val indented = job.linesIterator.map(l => if l.isEmpty then l else s"  $l").mkString("\n")
      assertTrue(
        body.contains(indented),
        job.contains("test-core:"),
        job.contains("if: github.ref == 'refs/heads/main'"),
        job.contains("MY_TOKEN: abc"),
        !job.contains("name: CI"),
        !job.contains("jobs:"),
      )
    },
    test("renderJobs preserves ListMap order and matches each renderJob") {
      val both = Render.renderJobs(sample.jobs)
      assertTrue(
        both.indexOf("test-workflow:") < both.indexOf("test-core:"),
        both.contains(Render.renderJob("test-workflow", sample.jobs("test-workflow")).trim) ||
          both.startsWith("test-workflow:"),
        Render.renderJobs(ListMap("test-core" -> sample.jobs("test-core"))) ==
          Render.renderJob("test-core", sample.jobs("test-core")),
      )
    },
    test("renderSteps encodes a step sequence") {
      val steps = Render.renderSteps(
        List(
          Step(uses = Some("actions/checkout@v4")),
          Step(name = Some("Test"), run = Some("sbt test")),
        )
      )
      assertTrue(
        steps.contains("- uses: actions/checkout@v4"),
        steps.contains("- name: Test"),
        steps.contains("run: sbt test"),
      )
    },
    test("renderMapping prints a flat string map") {
      val out = Render.renderMapping(ListMap("packages" -> "write", "contents" -> "read"))
      assertTrue(
        out.contains("packages: write"),
        out.contains("contents: read"),
        Render.renderMapping(Map.empty) == "",
      )
    },
  )
end RenderSpec
