package zipx.workflow

import zio.blocks.chunk.Chunk
import zio.blocks.schema.*
import zio.blocks.schema.yaml.*
import scala.collection.immutable.ListMap

/** Renders a [[Workflow]] to deterministic GitHub Actions YAML.
  *
  * Jobs and steps go through zio-blocks' derived codecs; only the top-level `Workflow` is hand-encoded, so that the
  * `on:` block can emit underscore event keys the kebab-casing deriver cannot produce and `jobs:` keeps its `ListMap`
  * order. Derivation is purely structural and ignores custom nested codecs, so that override has to live at the level
  * owning the key: a `YamlCodec[Workflow]`, not a `given` on `Triggers`.
  *
  * The fragment helpers share [[render]]'s encode + prune + print pipeline, which is what makes a doc snippet or unit
  * test byte-comparable with the committed `ci.yml`.
  */
object Render:

  private val jobCodec: YamlCodec[Job]                 = Schema[Job].derive(YamlFormat)
  private val stepCodec: YamlCodec[Step]               = Schema[Step].derive(YamlFormat)
  private val concurrencyCodec: YamlCodec[Concurrency] = Schema[Concurrency].derive(YamlFormat)

  /** The file as written to `.github/workflows`, header included. */
  def render(wf: Workflow): Either[String, String] =
    renderBody(wf).map(body => s"$header\n$body\n")

  /** No header, no trailing newline. */
  def renderBody(wf: Workflow): Either[String, String] =
    checked(wf.jobs.values.toList.flatMap(_.steps), workflowYaml(wf))

  /** One job as the mapping fragment it would be under `jobs:`. */
  def renderJob(id: String, job: Job): Either[String, String] =
    renderJobs(ListMap(id -> job))

  def renderJobs(jobs: ListMap[String, Job]): Either[String, String] =
    checked(jobs.values.toList.flatMap(_.steps), jobsYaml(jobs))

  def renderSteps(steps: List[Step]): Either[String, String] =
    checked(steps, Yaml.Sequence(Chunk.from(steps.map(encodeStep))))

  /** The single funnel for both layers' render-time rules: [[Step.problem]] is GitHub's step shape, which the case
    * class cannot encode, and [[YamlPrinter.problem]] is content that would print as YAML GitHub cannot parse. The
    * failure is a value, and nothing reaches disk when either fires, because the caller decides what a bad workflow
    * means: `zipxWorkflowGenerate` makes it a build failure, a test asserts on it.
    */
  private def checked(steps: List[Step], yaml: => Yaml): Either[String, String] =
    steps.flatMap(Step.problem).headOption match
      case Some(error) => Left(error)
      case None        =>
        val pruned = prune(yaml)
        YamlPrinter.problem(pruned).toLeft(YamlPrinter.print(pruned))

  private def encodeStep(step: Step): Yaml =
    prune(stepCodec.encodeValue(step))

  /** A `permissions:`, `env:` or `with:` block on its own. Empty renders as the empty string. */
  def renderMapping(entries: Map[String, String]): Either[String, String] =
    if entries.isEmpty then Right("")
    else print(Yaml.Mapping(Chunk.from(entries.map((k, v) => (Yaml.Scalar(k), Yaml.Scalar(v))))))

  /** Checks [[YamlPrinter.problem]] but not [[Step.problem]]: no `Step` is reachable from a bare tree. */
  def print(yaml: Yaml): Either[String, String] =
    val pruned = prune(yaml)
    YamlPrinter.problem(pruned).toLeft(YamlPrinter.print(pruned))

  val header: String =
    "# Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  private def workflowYaml(wf: Workflow): Yaml =
    val entries = Chunk.from(
      scalar("name", wf.name) ++
        Seq("on" -> triggersYaml(wf.on)) ++
        mapEntry("permissions", wf.permissions) ++
        mapEntry("env", wf.env) ++
        wf.concurrency.map(c => "concurrency" -> concurrencyCodec.encodeValue(c)) ++
        Seq("jobs" -> jobsYaml(wf.jobs))
    )
    Yaml.Mapping(entries.map((k, v) => (Yaml.Scalar(k), v)))
  end workflowYaml

  /** Hand-built because GitHub's event keys are `pull_request` and `workflow_dispatch`, which kebab-casing would
    * mangle.
    */
  private def triggersYaml(t: Triggers): Yaml =
    val scheduleEntry =
      if t.schedule.isEmpty then Nil
      else
        Seq(
          "schedule" -> Yaml.Sequence(
            Chunk.from(t.schedule.map(c => Yaml.Mapping.fromStringKeys("cron" -> Yaml.Scalar(c.render))))
          )
        )
    val entries =
      t.push.map(b => "push" -> branchFilterYaml(b)).toSeq ++
        t.pullRequest.map(b => "pull_request" -> branchFilterYaml(b)) ++
        scheduleEntry ++
        (if t.workflowDispatch then Seq("workflow_dispatch" -> Yaml.NullValue) else Nil) ++
        (if t.workflowCall then Seq("workflow_call" -> Yaml.NullValue) else Nil)
    Yaml.Mapping.fromStringKeys(entries*)
  end triggersYaml

  private def branchFilterYaml(b: BranchFilter): Yaml =
    val entries =
      seqEntry("branches", b.branches) ++
        seqEntry("tags", b.tags) ++
        seqEntry("paths", b.paths)
    if entries.isEmpty then Yaml.NullValue else Yaml.Mapping.fromStringKeys(entries*)

  private def jobsYaml(jobs: ListMap[String, Job]): Yaml =
    Yaml.Mapping(
      Chunk.from(jobs.map((id, job) => (Yaml.Scalar(id), encodeJob(job))))
    )

  private def encodeJob(job: Job): Yaml =
    collapseSingletonRunsOn(prune(jobCodec.encodeValue(job)))

  /** The derived codec renders `runsOn: List[String]` as a sequence, but GitHub's convention for a single label is a
    * scalar. Multi-label runners stay a sequence.
    */
  private def collapseSingletonRunsOn(job: Yaml): Yaml = job match
    case Yaml.Mapping(entries) =>
      Yaml.Mapping(entries.map {
        case (k @ Yaml.Scalar("runs-on", _), Yaml.Sequence(labels)) if labels.length == 1 => (k, labels(0))
        case other                                                                        => other
      })
    case other => other

  private def scalar(k: String, v: String): Seq[(String, Yaml)]                = Seq(k -> Yaml.Scalar(v))
  private def mapEntry(k: String, m: Map[String, String]): Seq[(String, Yaml)] =
    if m.isEmpty then Nil
    else Seq(k -> Yaml.Mapping(Chunk.from(m.map((mk, mv) => (Yaml.Scalar(mk), Yaml.Scalar(mv))))))
  private def seqEntry(k: String, xs: List[String]): Seq[(String, Yaml)] =
    if xs.isEmpty then Nil else Seq(k -> Yaml.Sequence(Chunk.from(xs.map(Yaml.Scalar(_)))))

  /** Drops empty mappings and sequences, so an absent collection does not render as `{}` or `[]`. Explicit `null`
    * survives. Applied to the fully-assembled tree, which is what also cleans up the derived codecs' `env: {}` and
    * `needs: []`.
    */
  def prune(y: Yaml): Yaml = y match
    case Yaml.Mapping(entries) =>
      val kept = entries.map((k, v) => (k, prune(v))).filter((_, v) => !isEmptyCollection(v))
      Yaml.Mapping(kept)
    case Yaml.Sequence(elems) =>
      Yaml.Sequence(elems.map(prune))
    case other => other

  private def isEmptyCollection(y: Yaml): Boolean = y match
    case Yaml.Mapping(entries) => entries.isEmpty
    case Yaml.Sequence(elems)  => elems.isEmpty
    case _                     => false

end Render
