package zipx.workflow

import zio.blocks.chunk.Chunk
import zio.blocks.schema.*
import zio.blocks.schema.yaml.*
import scala.collection.immutable.ListMap

/** Renders a [[Workflow]] to deterministic GitHub Actions YAML.
  *
  * Strategy (see [[zipx.workflow]] package doc and the project memory `zipx-yaml-rendering`):
  *   - Job/Step/Strategy/Concurrency are rendered by zio-blocks' derived YAML codecs, which kebab-case field names —
  *     precisely GitHub's convention for those keys (`runs-on`, `timeout-minutes`, `fail-fast`, ...).
  *   - The top-level `Workflow` is hand-encoded so the `on:` block can emit underscore event keys (`pull_request`,
  *     `workflow_dispatch`) that the kebab-casing deriver cannot produce, and so the `jobs:` mapping preserves the
  *     `ListMap` order. Derivation is purely structural and ignores custom nested codecs, so the override must live at
  *     the level that owns the key — hence a `YamlCodec[Workflow]`, not a `given` on `Triggers`.
  *   - A final [[prune]] pass drops empty mappings/sequences (an empty `env`/`with`/`needs`) so they don't render as
  *     `{}` / `[]`, while preserving explicit `null`.
  */
object Render:

  private val jobCodec: YamlCodec[Job]                 = Schema[Job].derive(YamlFormat)
  private val concurrencyCodec: YamlCodec[Concurrency] = Schema[Concurrency].derive(YamlFormat)

  /** Renders a workflow to a YAML string, ready to write into the `.github/workflows` directory.
    *
    * Output is deterministic: field order is fixed by construction, maps must be built with `ListMap`, and no
    * `Map`-iteration order is relied upon. A generated-by header is prepended so the file announces its provenance.
    */
  def render(wf: Workflow): String =
    val body = YamlPrinter.print(prune(workflowYaml(wf)))
    // Ensure exactly one trailing newline (POSIX text file; the printer omits it).
    s"$header\n$body\n"

  val header: String =
    "# Generated by zipx — do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate."

  /** The hand-assembled top-level mapping. Only present keys are emitted. */
  private def workflowYaml(wf: Workflow): Yaml =
    val entries = Chunk.from(
      scalar("name", wf.name) ++
        Seq("on" -> triggersYaml(wf.on)) ++
        mapEntry("permissions", wf.permissions) ++
        mapEntry("env", wf.env) ++
        wf.concurrency.map(c => "concurrency" -> concurrencyCodec.encodeValue(c)) ++
        Seq("jobs" -> jobsYaml(wf.jobs)),
    )
    Yaml.Mapping(entries.map((k, v) => (Yaml.Scalar(k), v)))
  end workflowYaml

  /** The `on:` block, hand-built with GitHub's exact underscore event keys. */
  private def triggersYaml(t: Triggers): Yaml =
    val entries =
      t.push.map(b => "push" -> branchFilterYaml(b)).toSeq ++
        t.pullRequest.map(b => "pull_request" -> branchFilterYaml(b)) ++
        (if t.workflowDispatch then Seq("workflow_dispatch" -> Yaml.NullValue) else Nil) ++
        (if t.workflowCall then Seq("workflow_call" -> Yaml.NullValue) else Nil)
    Yaml.Mapping.fromStringKeys(entries*)

  private def branchFilterYaml(b: BranchFilter): Yaml =
    val entries =
      seqEntry("branches", b.branches) ++
        seqEntry("tags", b.tags) ++
        seqEntry("paths", b.paths)
    if entries.isEmpty then Yaml.NullValue else Yaml.Mapping.fromStringKeys(entries*)

  private def jobsYaml(jobs: ListMap[String, Job]): Yaml =
    Yaml.Mapping(Chunk.from(jobs.map((id, job) => (Yaml.Scalar(id), collapseSingletonRunsOn(jobCodec.encodeValue(job))))))

  /** The derived codec renders `runsOn: List[String]` as a sequence. GitHub Actions convention (and every existing
    * golden) is a scalar for a single label — so collapse a one-element `runs-on` sequence to a scalar, leaving
    * multi-label runners as a sequence (`runs-on: [self-hosted, linux]`).
    */
  private def collapseSingletonRunsOn(job: Yaml): Yaml = job match
    case Yaml.Mapping(entries) =>
      Yaml.Mapping(entries.map {
        case (k @ Yaml.Scalar("runs-on", _), Yaml.Sequence(labels)) if labels.length == 1 => (k, labels(0))
        case other                                                                        => other
      })
    case other => other

  private def scalar(k: String, v: String): Seq[(String, Yaml)]                = Seq(k -> Yaml.Scalar(v))
  private def mapEntry(k: String, m: Map[String, String]): Seq[(String, Yaml)] =
    if m.isEmpty then Nil
    else Seq(k -> Yaml.Mapping(Chunk.from(m.map((mk, mv) => (Yaml.Scalar(mk), Yaml.Scalar(mv))))))
  private def seqEntry(k: String, xs: List[String]): Seq[(String, Yaml)] =
    if xs.isEmpty then Nil else Seq(k -> Yaml.Sequence(Chunk.from(xs.map(Yaml.Scalar(_)))))

  /** Recursively drop empty mappings and sequences so absent collections don't render as `{}` / `[]`. Preserves
    * explicit `null` and non-empty structures. Applied to the fully-assembled tree so it also cleans the output of the
    * derived job/step codecs (which emit `env: {}`, `needs: []`, etc.).
    */
  def prune(y: Yaml): Yaml = y match
    case Yaml.Mapping(entries) =>
      val kept = entries.map((k, v) => (k, prune(v))).filter((_, v) => !isEmptyCollection(v))
      Yaml.Mapping(kept)
    case Yaml.Sequence(elems) =>
      Yaml.Sequence(elems.map(prune))
    case other => other

  private def isEmptyCollection(y: Yaml): Boolean = y match
    case Yaml.Mapping(entries) => entries.isEmpty
    case Yaml.Sequence(elems)  => elems.isEmpty
    case _                     => false

end Render
