ThisBuild / scalaVersion := ZipxVersions.scala3
version                  := "1.0.0-ci"
zipxCacheEpoch           := CacheEpoch.Fixed("1.0.0-ci")

libraryDependencies ++= ZipxDeps(ZipxVersions.zio)

zipxVersions  := ZipxVersions.coords
zipxSbt       := Some(ZipxVersions.sbt)
zipxScala     := Some(ZipxVersions.scala3)
zipxCheckDeps := true

lazy val root = (project in file("."))
  .settings(publish / skip := true)

val assertVersions = taskKey[Unit]("assert generated plugins.sbt and build.properties")
assertVersions := {
  val rootDir = (LocalRootProject / baseDirectory).value
  val plugins = IO.read(rootDir / "project" / "plugins.sbt")
  val props   = IO.read(rootDir / "project" / "build.properties")
  assert(plugins.startsWith("// Generated by zipx."), "plugins.sbt should start with the generated header")
  assert(
    plugins.contains("""addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" %"""),
    "plugins.sbt should emit loaded sbt-zipx first",
  )
  assert(
    plugins.contains("""addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")"""),
    "plugins.sbt should emit catalog plugins",
  )
  assert(plugins.indexOf("sbt-zipx") < plugins.indexOf("sbt-scalafmt"), "sbt-zipx should be first")
  assert(props.contains("sbt.version=2.0.6"), s"build.properties should pin sbt 2.0.6, got $props")
  assert(props.startsWith("# Generated by zipx."), "build.properties should start with the generated header")
}
