// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.14.1")
addSbtPlugin("com.jamesward" % "sbt-reload" % "0.0.7")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin(("org.scala-sbt" % "sbt-remote-cache" % "2.0.8").excludeAll(ExclusionRule(organization = "org.scala-sbt")))
