// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.18.1")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin(("org.scala-sbt" % "sbt-remote-cache" % "2.1.0-M3").excludeAll(ExclusionRule(organization = "org.scala-sbt")))
