package zipx.core

import zio.test.*

object ScalaStewardConfigSpec extends ZIOSpecDefault:

  def spec = suite("ScalaStewardConfig")(
    test("renders a pullRequests.grouping block with a generated-file header") {
      val out = ScalaStewardConfig.render(ScalaStewardConfig.Defaults)
      assertTrue(
        out.startsWith("# Generated by zipx"),
        out.contains("pullRequests.grouping = ["),
        out.endsWith("]\n"),
      )
    },
    test("family groups precede the version groups, which precede the catch-all") {
      val out         = ScalaStewardConfig.render(ScalaStewardConfig.Defaults)
      val earlyeffect = out.indexOf("\"rocks.earlyeffect\"")
      val zio         = out.indexOf("\"dev.zio\"")
      val minor       = out.indexOf("version = \"minor\"")
      val major       = out.indexOf("version = \"major\"")
      val catchAll    = out.indexOf("group = \"*\"")
      assertTrue(
        earlyeffect > 0,
        earlyeffect < minor,
        zio > 0 && zio < minor,
        minor < major,
        major < catchAll,
        catchAll == out.lastIndexOf("group = \"*\""),
      )
    },
    test("defaults keep patch riding with minor and end in a net") {
      val minor = ScalaStewardConfig.Defaults.find(_.name == "minor").get
      assertTrue(
        minor.filter.flatMap(_.version).toSet ==
          Set("minor", "patch", "pre-release", "build-metadata"),
        ScalaStewardConfig.Defaults.last.filter == List(StewardFilter(group = Some("*"))),
      )
    },
    test("omits absent fields and quotes present ones") {
      val out = ScalaStewardConfig.render(
        List(StewardGroup(name = "only", filter = List(StewardFilter(artifact = Some("zio-test")))))
      )
      assertTrue(
        out.contains("{ name = \"only\", filter = [{ artifact = \"zio-test\" }] }"),
        !out.contains("title"),
        !out.contains("group ="),
        !out.contains("version ="),
      )
    },
    test("rejects an empty group list, a nameless group, and a predicate-free filter") {
      def fails(thunk: => String): Boolean =
        try
          thunk; false
        catch case _: IllegalArgumentException => true

      assertTrue(
        fails(ScalaStewardConfig.render(Nil)),
        fails(
          ScalaStewardConfig.render(List(StewardGroup(name = " ", filter = List(StewardFilter(group = Some("a"))))))
        ),
        fails(ScalaStewardConfig.render(List(StewardGroup(name = "a", filter = Nil)))),
        fails(ScalaStewardConfig.render(List(StewardGroup(name = "a", filter = List(StewardFilter()))))),
      )
    },
  )
end ScalaStewardConfigSpec
